module.exports = function(sequelize, DataTypes) {
  var user = sequelize.define("user", {
   
    first_name:{ 
        type:DataTypes.STRING,
        allowNull:false
      
    },
    last_name:{
        type:DataTypes.STRING,
        allowNull:false
    },
    email:{
        type:DataTypes.STRING,
        allowNull:false,
        validate:{
            isEmail:true
        }
    },
    verified:{
        type:DataTypes.BOOLEAN,
        allowNull:true,
        defaultValue:"1"
    },
    username:{
        type:DataTypes.STRING,
        allowNull:false

    },
    password:{
        type:DataTypes.STRING,
        allowNull:false
    },
    FavGame1:{
        type:DataTypes.STRING
    },
    FavGame2:{
        type:DataTypes.STRING
    },
    FavGame3:{
        type:DataTypes.STRING
    },
    zipcode:{
        type:DataTypes.INTEGER(5)
    },
    ninSwitch:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    ps4:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    xbox1:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    nin3ds:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    ninwu:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    pc:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    rpg:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    sports:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    simulator:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    adventure:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    action:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    actionAdventure:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    date_created:{
        type:DataTypes.DATE,
        defaultValue:DataTypes.NOW

    }
  
 });

  return user;
};